(require '[clojure.string :as str])

(-> (slurp "./input/day08.txt")
    (->> (str/split-lines)
         (map #(last (str/split % #"\|\s")))
         (map #(str/split % #" ")))
    (->> (flatten)
         (map count)
         (filter (complement #(<= 5 % 6)))
         (count)))
